# This config file is used by ros2_control
/**:
  controller_manager:
    ros__parameters:
      update_rate: 500  # Hz
      # is_async: true
          
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      imu_sensor_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster
      tita_controller:
        type: tita_locomotion/TitaController
      template_ros2_controller:
        type: tita_locomotion/TemplateRos2Controller
      effort_controller:
        type: effort_controllers/JointGroupEffortController

  imu_sensor_broadcaster:
    ros__parameters:
      update_rate: 500  # Hz
      sensor_name: imu
      frame_id:  imu
  joint_state_broadcaster:
    ros__parameters:
      update_rate: 500  # Hz

  tita_controller:
    ros__parameters:
      update_rate: 500  # Hz
      joints:
        - left_hip_joint
        - left_knee_joint
        - left_wheel_joint
        - right_hip_joint
        - right_knee_joint
        - right_wheel_joint
      command_interfaces:
        - position
        - velocity
        - effort
        - kp
        - kd
      state_interfaces:
        - position
        - velocity
        - effort
      sensors:
        - imu

  template_ros2_controller:
    ros__parameters:
      update_rate: 500  # Hz
      joints:
        - left_hip_joint
        - left_knee_joint
        - left_wheel_joint
        - right_hip_joint
        - right_knee_joint
        - right_wheel_joint
      command_interfaces:
        # - position
        # - velocity
        - effort
        # - kp
        # - kd
      state_interfaces:
        - position
        - velocity
        - effort
      sensors:
        - imu
  
  effort_controller:
    ros__parameters:
      joints:
        - left_hip_joint
        - left_knee_joint
        - left_wheel_joint
        - right_hip_joint
        - right_knee_joint
        - right_wheel_joint
